# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LFg1h3C_olt8-64kXNPX77jZcwhRL1CN
"""

from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

data

data.keys()

dscr = data['DESCR']

dscr

print(dscr)

data['data'].shape

data['feature_names']

data['data'][0] #for all 30 features

#Map the features
j= 0
for i in data['feature_names']:
  print(i , ":" , data['data'][0][j])
  j = j+1

j= 0
for i in data['feature_names']:
  print(i , ":" , data['data'][568][j])
  j = j+1

#Names of the target
data['target_names']

#Target data
data['target']

data['target'].shape

data['filename']

"""#SECOND STAGE"""

feature = data['data']
feature

label = data['target']
label

feature.shape

label.shape

from sklearn.preprocessing import StandardScaler

scale = StandardScaler()

feature = scale.fit_transform(feature)

print(feature[0])
print(label[0])

j= 0
for i in data['feature_names']:
  print(i , ":" , feature[0][j])
  j = j+1

print(feature[0])
print(data['target_names'][label[0]])

import pandas as pd

df = pd.DataFrame(feature , columns = data['feature_names'])

df.head()

df.tail()

#500 training
x_train = feature[:500] 
y_train = label[:500]

#35 validation
x_val = feature[500:535] 
y_val = label[500:535]

#34 testing
x_test = feature[535:] 
y_test = label[535:]

x_train.shape

y_train.shape